<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;
defined('KRYSTAL') or die;

?>

<form data-group="block">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#page" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Announcement'); ?></a></li>
        <li role="presentation"><a href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Configuration'); ?></a></li>
	</ul>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="page" role="tabpanel">
            <div class="well">

                <?php if (count($languages) > 1): ?>
                <ul class="nav nav-tabs" role="tablist">
                    <?php foreach ($languages as $index => $language): ?>
                    <li role="presentation" class="<?php echo $index == 0 ? 'active' : null; ?>"><a href="<?php printf('#language-%s', $language->getId()); ?>" role="tab" data-toggle="tab"><i class="<?php printf('famfamfam-flag-%s', $language->getFlag()); ?>"></i> <?php echo $language->getName(); ?></a></li>
                    <?php endforeach; ?>
                </ul>
                <?php endif; ?>

                <br />

                <div class="tab-content">
                    <?php foreach ($languages as $index => $language): ?>
                    <div class="tab-pane fade in <?php echo $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">

                        <?php $entity = LanguageManager::findByLangId($language->getId(), $block); ?>

                        <?php echo Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                        <?php echo Element::hidden(sprintf('translation[%s][web_page_id]', $language->getId()), $entity->getWebPageId()); ?>
                        <?php echo Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                        <h2 class="text-muted"><?php echo $language->getName(); ?></h2>
                        <br />

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), array('class' => 'form-control', 'readonly' => !$extendedMode, 'placeholder' => $this->translate("Block's name"))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-2 control-label"><?php $this->show('Content'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::textarea(sprintf('translation[%s][content]', $language->getId()), $entity->getContent(), array('class' => 'form-control', 'rows' => '7', 'placeholder' => $this->translate("Block's plain text content"))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>

        <div role="tabpanel" class="tab-pane" id="configuration">
            <div class="well">
                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Class'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::text('block[class]', $entity->getClass(), array('class' => 'form-control', 'placeholder' => $this->translate("Class's name to simplify rendering"))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php if (!$new): ?>
    <button data-button="save" data-url="<?php echo $this->url('Block:Admin:Block@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Save'); ?></button>
	<button data-button="save-create" data-back-url="<?php echo $this->url('Block:Admin:Block@addAction'); ?>" data-url="<?php echo $this->url('Block:Admin:Block@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Save & Create new'); ?></button>

    <?php else: ?>
	<button data-button="add" data-back-url="<?php echo $this->url('Block:Admin:Block@editAction', null); ?>" data-url="<?php echo $this->url('Block:Admin:Block@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-save"></i> <?php $this->show('Add'); ?></button>
	<button data-button="add-create" data-url="<?php echo $this->url('Block:Admin:Block@saveAction'); ?>" class="btn btn-primary"><i class="glyphicon glyphicon-floppy-open"></i> <?php $this->show('Add & Create new'); ?></button>
	<?php endif; ?>

    <button data-button="cancel" data-url="<?php echo $this->url('Block:Admin:Block@gridAction'); ?>" class="btn btn-default"><i class="glyphicon glyphicon-floppy-remove"></i> <?php $this->show('Cancel'); ?></button>
</form>
