<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;

$translatable = isset($block[0]) ? $block[0]->getTranslatable() : $block->getTranslatable();

?>

<form class="card" autocomplete="off">
    <?php if ($translatable): ?>
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item">
            <a class="nav-link active" href="#page" role="tab" data-bs-toggle="tab"><i class="fas fa-otter"></i> <?= $this->translate('Block') ?></a>
        </li>
        <li role="presentation" class="nav-item">
            <a class="nav-link" href="#configuration" role="tab" data-bs-toggle="tab"><i class="fas fa-tasks"></i> <?= $this->translate('Configuration') ?></a>
        </li>
    </ul>
    <?php endif; ?>

    <div class="tab-content">
        <?php if ($translatable): ?>
        <div class="tab-pane fade show active" id="page" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <div class="tab-pane fade <?= $index == 0 ? 'show active' : '' ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">

                    <?php $entity = LanguageManager::findByLangId($language->getId(), $block); ?>

                    <?= Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()) ?>
                    <?= Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()) ?>

                    <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                    <div class="mb-3 row">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Content') ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?= Element::textarea(sprintf('translation[%s][content]', $language->getId()), $entity->getContent(), ['class' => 'form-control', 'rows' => '7', 'placeholder' => $this->translate("Block's plain text content")]) ?>
                                <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
        <?php else: ?>
        <?php $entity = isset($block[0]) ? $block[0] : $block; ?>
        <?php endif; ?>

        <div role="tabpanel" class="<?= $translatable ? 'tab-pane' : null ?>">
            <?= Element::hidden('block[id]', $entity->getId()) ?>
            <?= Element::hidden('block[translatable]', $entity->getTranslatable()) ?>

            <div class="mb-3 row">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Name') ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?= Element::text('block[name]', $entity->getName(), ['class' => 'form-control']) ?>
                        <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                    </div>
                </div>
            </div>

            <?php if (!$entity->getTranslatable()): ?>
            <div class="mb-3 row">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Value') ?></label>
                <div class="col-lg-10">
                    <?= Element::textarea('block[value]', $entity->getValue(), ['class' => 'form-control']) ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$entity->getId(),
        'add' => 'Block:Admin:Block@addAction',
        'edit' => 'Block:Admin:Block@editAction',
        'save' => 'Block:Admin:Block@saveAction',
        'cancel' => 'Block:Admin:Block@indexAction'
    ]); ?>

</form>