<?php

use Krystal\Form\Element;
use Cms\Service\LanguageManager;
defined('KRYSTAL') or die;

$translatable = $block[0]->getTranslatable();

?>

<form class="card" data-group="block" autocomplete="off">
    <?php if ($translatable): ?>
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item active"><a class="nav-link" href="#page" role="tab" data-toggle="tab"><i class="fas fa-box-open"></i> <?php $this->show('Block'); ?></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#configuration" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-th-list"></i> <?php $this->show('Configuration'); ?></a></li>
	</ul>
    <?php endif; ?>

    <div class="tab-content">
        <?php if ($translatable): ?>
        <div class="tab-pane fade in active" id="page" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <div class="tab-pane fade in <?php echo $index == 0 ? 'active' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">

                    <?php $entity = LanguageManager::findByLangId($language->getId(), $block); ?>

                    <?php echo Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?php echo Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>

                    <?php $this->loadPartial('language-name', array('language' => $language)); ?>

                    <div class="form-group">
                        <label class="col-lg-2 control-label"><?php $this->show('Content'); ?></label>
                        <div class="col-lg-10">
                            <div class="input-group">
                                <?php echo Element::textarea(sprintf('translation[%s][content]', $language->getId()), $entity->getContent(), array('class' => 'form-control', 'rows' => '7', 'placeholder' => $this->translate("Block's plain text content"))); ?>
                                <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
        <?php else: ?>
        <?php $entity = $block[0]; ?>
        <?php endif; ?>

        <div role="tabpanel" class="<?= $translatable ? 'tab-pane' : null; ?>" id="configuration">
            <?php echo Element::hidden('block[id]', $entity->getId()); ?>

            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::text('block[name]', $entity->getName(), array('class' => 'form-control')); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                </div>
            </div>

            <?php if (!$entity->getTranslatable()): ?>
            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Value'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::textarea('block[value]', $entity->getValue(), array('class' => 'form-control')); ?>
                </div>
            </div>
            <?php endif; ?>

            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Translatable'); ?></label>
                <div class="col-lg-10">
                    <?php echo Element::checkbox('block[translatable]', $entity->getTranslatable()); ?>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label"><?php $this->show('Class'); ?></label>
                <div class="col-lg-10">
                    <div class="input-group">
                        <?php echo Element::text('block[class]', $entity->getClass(), array('class' => 'form-control', 'placeholder' => $this->translate("Class's name to simplify rendering"))); ?>
                        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php $this->loadPartial('actions', array(
        'new' => !$entity->getId(),
        'add' => 'Block:Admin:Block@addAction',
        'edit' => 'Block:Admin:Block@editAction',
        'save' => 'Block:Admin:Block@saveAction',
        'cancel' => 'Block:Admin:Block@gridAction'
    )); ?>

</form>
