<?php

use Krystal\Grid\Grid;
use Krystal\Form\Element;

defined('KRYSTAL') or die;

?>

<?php if ($extendedMode): ?>
<div class="btn-toolbar">
	<div class="btn-group">
	  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
		<i class="glyphicon glyphicon-list"></i> <?php $this->show('Menu'); ?> <span class="caret"></span>
	  </button>
	  <ul class="dropdown-menu">
		 <li><a href="<?php echo $this->url('Block:Admin:Block@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new block'); ?></a></li>
		 <li><a href="<?php echo $this->url('Block:Admin:Category@addAction'); ?>"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Add new category'); ?></a></li>
		 <li class="divider"></li>
		 <li class="dropdown-header"><?php $this->show('Actions'); ?></li>
		 
		 <?php if (!empty($blocks)): ?>
		 <li><a href="#" data-button="remove-selected" data-url="<?php echo $this->url('Block:Admin:Block@deleteAction', null); ?>"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php else: ?>
		 <li class="disabled"><a><i class="glyphicon glyphicon-remove"></i> <?php $this->show('Remove selected'); ?></a></li>
		 <?php endif; ?>
	  </ul>
	</div>
</div>
<?php endif; ?>


<div class="row">
    <div class="col-lg-7">
        <?php $this->loadPartial('items-per-page', array('caption' => 'HTML Blocks')); ?>

        <form>
            <div class="table-responsive">
                <table class="table table-hover table-bordered table-striped">
                    <thead>
                        <tr>
                            <?php if ($extendedMode): ?>
                            <th class="text-center">
                                <?php if (!empty($blocks)): ?>
                                <input type="checkbox" />
                                <?php endif; ?>
                            </th>
                            <?php endif; ?>
                            
                            <th class="text-center"><?php $this->show('#'); ?></th>
                            <th class="text-center"><?php $this->show('Name'); ?></th>
                            
                            <?php if ($extendedMode): ?>
                            <th class="text-center"><?php $this->show('Class'); ?></th>
                            <?php endif; ?>
                            
                            <th class="text-center"><?php $this->show('Actions'); ?></th>
                        </tr>
                    </thead>
                    
                    <?php if (!empty($blocks)): ?>
                    <tbody>
                        <?php foreach ($blocks as $block): ?>
                        <tr>
                            <?php if ($extendedMode): ?>
                            <td class="text-center">
                                <input type="checkbox" name="toDelete[<?php echo $block->getId(); ?>]" />
                            </td>
                            <?php endif; ?>
                            <td class="text-center text-muted"><?php echo $block->getId(); ?></td>
                            <td class="text-center"><?php echo $block->getName(); ?></td>
                            
                            <?php if ($extendedMode): ?>
                            <td class="text-center"><?php echo $block->getClass(); ?></td>
                            <?php endif; ?>
                            
                            <td class="text-center">
                                <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Edit this block'); ?>" data-button="edit" href="<?php echo $this->url('Block:Admin:Block@editAction', $block->getId()); ?>"><i class="glyphicon glyphicon-pencil"></i></a>

                                <?php if ($extendedMode): ?>
                                <a data-toggle="tooltip" data-placement="left" data-original-title="<?php $this->show('Remove this block'); ?>" data-button="delete" data-url="<?php echo $this->url('Block:Admin:Block@deleteAction', $block->getId()); ?>" href="#" ><i class="glyphicon glyphicon-remove"></i></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                        
                    </tbody>
                    <?php endif; ?>
                    
                </table>
                
                <?php if (empty($blocks)): ?>
                <div class="center-block">
                    <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No blocks'); ?></h2>
                </div>
                <?php endif; ?>
                
            </div>
        </form>

        <?php $this->loadPartial('paginator'); ?>        
    </div>

    <div class="col-lg-5">
        <h2><i class="glyphicon glyphicon-th-large"></i> <?php $this->show('Categories'); ?> <small>(<?= count($categories); ?>)</small></h2>

        <?= Grid::render($categories, array(
            // A column to be considered as a primary key
            'pk' => 'id',
            'tableClass' => 'table table-hover table-bordered table-striped table-condensed',
            'columns' => array(
                array(
                    'column' => 'id',
                    'label' => '#'
                ),

                array(
                    'column' => 'name',
                ),

                array(
                    'column' => 'field_count',
                    'label' => 'Field count'
                )
            ),

            'actions' => array(
                'edit' => function($row){
                    return Element::icon('glyphicon glyphicon-pencil', $this->url('Block:Admin:Category@editAction', $row['id']), array('data-toggle' => 'tooltip', 'data-placement' => 'left', 'data-original-title' => $this->translate('Edit this category'), 'data-button' => 'edit'));
                },

                'remove' => function($row){
                    return Element::icon('glyphicon glyphicon-remove', '#', array('data-toggle' => 'tooltip', 'data-placement' => 'left', 'data-original-title' => $this->translate('Remove this category'), 'data-button' => 'delete', 'data-url' => $this->url('Block:Admin:Category@deleteAction', $row['id'])));
                }
            )

        ), $this->translator); ?>
    </div>
</div>

