<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Block\Collection\FieldTypeCollection;
use Cms\View\Icon;

?>

<div class="card">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item">
            <a class="nav-link active" href="#category" role="tab" data-bs-toggle="tab"><i class="fas fa-tags"></i> <?= $this->translate('Category') ?></a>
        </li>

        <?php if ($category->getId()): ?>
        <li role="presentation" class="nav-item">
            <a class="nav-link" href="#fields" role="tab" data-bs-toggle="tab"><i class="fas fa-tasks"></i> <?= $this->translate('Fields') ?> <small class="text-muted">(<?= count($fields) ?>)</small></a>
        </li>
        <?php endif; ?>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade show active" id="category" role="tabpanel">
            <form autocomplete="off">
                <?= Element::hidden('category[id]', $category->getId()) ?>

                <div class="mb-3 row">
                    <label class="col-lg-2 col-form-label"><?= $this->translate('Name') ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?= Element::text('category[name]', $category->getName(), ['class' => 'form-control', 'placeholder' => $this->translate('Category name')]) ?>
                            <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                        </div>
                    </div>
                </div>

                <?php $this->loadPartial('actions', [
                    'new' => !$category->getId(),
                    'add' => 'Block:Admin:Category@addAction',
                    'edit' => 'Block:Admin:Category@editAction',
                    'save' => 'Block:Admin:Category@saveAction',
                    'cancel' => 'Block:Admin:Block@indexAction'
                ]); ?>

            </form>
        </div>

        <?php if ($category->getId()): ?>
        <div class="tab-pane fade" id="fields" role="tabpanel">
            <div class="row">
                <div class="col-lg-6">
                    <h2 class="mt-3 mb-4"><i class="fas fa-tasks"></i> <?= $this->translate('Fields') ?> <small>(<?= count($fields) ?>)</small></h2>

                    <?= $this->widget(new GridViewWidget($fields, [
                        'pk' => 'id',
                        'tableClass' => 'table table-hover table-bordered table-striped align-middle',
                        'rowAttributes' => [
                            'class' => function ($row) use ($field) {
                                if ($row->getId() == $field->getId()) {
                                    return 'table-info';
                                }
                            }
                        ],

                        'columns' => [
                            [
                                'column' => 'id',
                                'label' => '#'
                            ],

                            [
                                'column' => 'name',
                                'attributes' => [
                                    'class' => null
                                ]
                            ],

                            [
                                'column' => 'type',
                                'translateable' => true,
                                'value' => function ($row) {
                                    $fTypeCol = new FieldTypeCollection();
                                    return $fTypeCol->findByKey($row->getType());
                                }
                            ],

                            [
                                'column' => 'translatable',
                                'translateable' => true,
                                'value' => function ($row) {
                                    return $row['translatable'] == 1 ? 'Yes' : 'No';
                                }
                            ],
                        ],

                        'actions' => [
                            function ($row) {
                                return Icon::edit(
                                    $this->url('Block:Admin:CategoryField@editAction', $row['id']),
                                    $this->translate('Edit this category')
                                );
                            },

                            function ($row) {
                                return Icon::remove(
                                    $this->url('Block:Admin:CategoryField@deleteAction', $row['id']),
                                    $this->translate('Remove this category'),
                                    null,
                                    $this->url('Block:Admin:Category@editAction', $row['category_id'])
                                );
                            }
                        ]
                    ])); ?>
                </div>

                <div class="col-lg-6">
                    <form autocomplete="off">
                        <h2><i class="fas fa-pencil-alt"></i> <?= $this->translate(!$field->getId() ? 'Add new field' : 'Edit the field') ?></h2>
                        <br />

                        <?= Element::hidden('field[id]', $field->getId()) ?>
                        <?= Element::hidden('field[category_id]', $category->getId()) ?>

                        <div class="mb-3 row">
                            <label class="col-lg-12 col-form-label"><?= $this->translate('Name') ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::textarea('field[name]', $field->getName(), ['class' => 'form-control', 'placeholder' => $this->translate('Field name')]) ?>
                                    <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="mb-3 row">
                            <label class="col-lg-12 col-form-label"><?= $this->translate('Type') ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::select('field[type]', $this->translateArray($fieldTypes), $field->getType(), ['class' => 'form-select']) ?>
                                    <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="mb-3 row">
                            <label class="col-lg-12 col-form-label"><?= $this->translate('Translatable') ?></label>
                            <div class="col-lg-10">
                                <?= Element::checkbox('field[translatable]', $field->getTranslatable()) ?>
                            </div>
                        </div>

                        <?php $this->loadPartial('actions', [
                            'new' => !$field->getId(),
                            'add' => [$this->url('Block:Admin:CategoryField@addAction', $category->getId())],
                            'edit' => [$this->url('Block:Admin:CategoryField@editAction', '')],
                            'save' => 'Block:Admin:CategoryField@saveAction',
                            'cancel' => 'Block:Admin:Block@indexAction'
                        ]); ?>

                    </form>
                </div>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>