<?php

use Krystal\Widget\GridView\GridViewWidget;
use Krystal\Form\Element;
use Block\Collection\FieldTypeCollection;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<div class="card">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item active"><a class="nav-link" href="#category" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-file"></i> <?php $this->show('Category'); ?></a></li>

        <?php if ($category->getId()): ?>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#fields" role="tab" data-toggle="tab"><i class="glyphicon glyphicon-tasks"></i> <?php $this->show('Fields'); ?></a></li>
        <?php endif; ?>
    </ul>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="category" role="tabpanel">
            <form data-group="category" autocomplete="off">
                <?php echo Element::hidden('category[id]', $category->getId()); ?>

                <div class="form-group">
                    <label class="col-lg-2 control-label"><?php $this->show('Name'); ?></label>
                    <div class="col-lg-10">
                        <div class="input-group">
                            <?php echo Element::text('category[name]', $category->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Category name'))); ?>
                            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                        </div>
                    </div>
                </div>

                <?php $this->loadPartial('actions', array(
                    'new' => !$category->getId(),
                    'add' => 'Block:Admin:Category@addAction',
                    'edit' => 'Block:Admin:Category@editAction',
                    'save' => 'Block:Admin:Category@saveAction',
                    'cancel' => 'Block:Admin:Block@gridAction'
                )); ?>

            </form>                
        </div>

        <?php if ($category->getId()): ?>
        <div class="tab-pane fade in" id="fields" role="tabpanel">
            <div class="row">
                <div class="col-lg-6">
                    <h2><i class="glyphicon glyphicon-th-large"></i> <?php $this->show('Fields'); ?> <small>(<?= count($fields); ?>)</small></h2>

                    <?= $this->widget(new GridViewWidget($fields, array(
                        'pk' => 'id',
                        'tableClass' => 'table table-hover table-bordered table-striped',
                        'rowAttributes' => array(
                            'class' => function($row) use ($field){
                                if ($row->getId() == $field->getId()) {
                                    return 'table-info';
                                }
                            }
                        ),

                        'columns' => array(
                            array(
                                'column' => 'id',
                                'label' => '#'
                            ),

                            array(
                                'column' => 'name',
                            ),

                            array(
                                'column' => 'type',
                                'translateable' => true,
                                'value' => function($row){
                                    $fTypeCol = new FieldTypeCollection();
                                    return $fTypeCol->findByKey($row->getType());
                                }
                            )
                        ),

                        'actions' => array(
                            'edit' => function($row){
                                return Icon::edit(
                                    $this->url('Block:Admin:CategoryField@editAction', $row['id']),
                                    $this->translate('Edit this category')
                                );
                            },

                            'remove' => function($row){
                                return Icon::remove(
                                    $this->url('Block:Admin:CategoryField@deleteAction', $row['id']),
                                    $this->translate('Remove this category')
                                );
                            }
                        )
                    ))); ?>
                </div>

                <div class="col-lg-6">
                    <form data-group="field" autocomplete="off">
                        <h2><i class="glyphicon glyphicon-pencil"></i> <?php $this->show(!$field->getId() ? 'Add new field' : 'Edit the field'); ?></h2>
                        <br />

                        <?php echo Element::hidden('field[id]', $field->getId()); ?>
                        <?php echo Element::hidden('field[category_id]', $category->getId()); ?>

                        <div class="form-group">
                            <label class="col-lg-12 control-label"><?php $this->show('Name'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::text('field[name]', $field->getName(), array('class' => 'form-control', 'placeholder' => $this->translate('Field name'))); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-12 control-label"><?php $this->show('Type'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?php echo Element::select('field[type]', $this->translateArray($fieldTypes), $field->getType(), array('class' => 'form-control')); ?>
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <?php $this->loadPartial('actions', array(
                            'new' => !$field->getId(),
                            'add' => array($this->url('Block:Admin:CategoryField@addAction', $category->getId())),
                            'edit' => 'Block:Admin:CategoryField@editAction',
                            'save' => 'Block:Admin:CategoryField@saveAction',
                            'cancel' => 'Block:Admin:Block@gridAction'
                        )); ?>

                    </form>                                   
                </div>
            </div>
        </div>
        <?php endif; ?>
    </div>
</div>
