<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

?>

<?php if ($extendedMode): ?>
<div class="btn-toolbar">
    <?php $this->loadPartial('menu', [
        'items' => [
            'Block:Admin:Block@addAction' => [
                'caption' => 'Add new block',
                'icon' => 'fas fa-otter'
            ],

            'Block:Admin:Block@addTranslatableAction' => [
                'caption' => 'Add new translatable block',
                'icon' => 'fas fa-otter'
            ],

            'Block:Admin:Category@addAction' => [
                'caption' => 'Add new category',
                'icon' => 'fas fa-tags'
            ]
        ],
        'actions' => [
            'data' => $blocks,
            'delete' => 'Block:Admin:Block@deleteAction'
        ]
    ]); ?>
</div>
<?php endif; ?>

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <?php $this->loadPartial('items-per-page', ['caption' => 'HTML Blocks']); ?>

            <form>
                <div class="table-responsive">
                    <?= $this->widget(new GridViewWidget($blocks, [
                        'pk' => 'id',
                        'tableClass' => 'table table-hover table-bordered table-striped align-middle',
                        'batch' => $extendedMode,
                        'columns' => [
                            [
                                'column' => 'id',
                                'label' => '#',
                                'attributes' => [
                                    'class' => 'text-center text-muted'
                                ]
                            ],

                            [
                                'column' => 'name',
                                'attributes' => [
                                    'class' => null
                                ]
                            ],

                            [
                                'column' => 'translatable',
                                'translateable' => true,
                                'value' => function ($row) {
                                    return boolval($row['translatable']) ? 'Yes' : 'No';
                                }
                            ],
                        ],

                        'actions' => [
                            function ($row) {
                                return Icon::edit(
                                    $this->url('Block:Admin:Block@editAction', $row['id']),
                                    $this->translate('Edit this block')
                                );
                            },

                            $extendedMode ? function ($row) {
                                return Icon::remove(
                                    $this->url('Block:Admin:Block@deleteAction', $row['id']),
                                    $this->translate('Remove this block')
                                );
                            } : null
                        ]
                    ])); ?>

                    <?php if (empty($blocks)): ?>
                    <div class="text-center my-4">
                        <h2 class="text-center text-muted"><i class="bi bi-x-circle"></i> <?= $this->translate('No blocks') ?></h2>
                    </div>
                    <?php endif; ?>
                </div>
            </form>

            <?php $this->loadPartial('paginator'); ?>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card">
            <h2 class="mb-3"><i class="fas fa-tags"></i> <?= $this->translate('Categories') ?> <small>(<?= count($categories) ?>)</small></h2>

            <?= $this->widget(new GridViewWidget($categories, [
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped align-middle',
                'columns' => [
                    [
                        'column' => 'id',
                        'label' => '#',
                        'attributes' => [
                            'class' => 'text-center text-muted'
                        ]
                    ],

                    [
                        'column' => 'name',
                        'attributes' => [
                            'class' => null
                        ]
                    ],

                    [
                        'column' => 'field_count',
                        'label' => 'Field count'
                    ]
                ],

                'actions' => [
                    function ($row) {
                        return Icon::edit(
                            $this->url('Block:Admin:Category@editAction', $row['id']),
                            $this->translate('Edit this category')
                        );
                    },

                    function ($row) {
                        return Icon::remove(
                            $this->url('Block:Admin:Category@deleteAction', $row['id']),
                            $this->translate('Remove this category')
                        );
                    }
                ]
            ])); ?>
        </div>
    </div>
</div>