<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<?php if ($extendedMode): ?>
<div class="btn-toolbar">
    <?php $this->loadPartial('menu', array(
        'items' => array(
            'Block:Admin:Block@addAction' => array(
                'caption' => 'Add new block',
                'icon' => 'fas fa-otter'
            ),

            'Block:Admin:Block@addTranslatableAction' => array(
                'caption' => 'Add new translatable block',
                'icon' => 'fas fa-otter'
            ),

            'Block:Admin:Category@addAction' => array(
                'caption' => 'Add new category',
                'icon' => 'fas fa-tags'
            )
        ),
        'actions' => array(
            'data' => $blocks,
            'delete' => 'Block:Admin:Block@deleteAction'
        )
    )); ?>
</div>
<?php endif; ?>

<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <?php $this->loadPartial('items-per-page', array('caption' => 'HTML Blocks')); ?>

            <form>
                <div class="table-responsive">
                    <?= $this->widget(new GridViewWidget($blocks, array(
                        'pk' => 'id',
                        'tableClass' => 'table table-hover table-bordered table-striped',
                        'batch' => $extendedMode,
                        'columns' => array(
                            array(
                                'column' => 'id',
                                'label' => '#',
                                'attributes' => array(
                                    'class' => 'text-center text-muted'
                                )
                            ),

                            array(
                                'column' => 'name',
                                'attributes' => array(
                                    'class' => null
                                )
                            ),

                            array(
                                'column' => 'translatable',
                                'translateable' => true,
                                'value' => function($row){
                                    return boolval($row['translatable']) ? 'Yes' : 'No';
                                }
                            ),
                        ),

                        'actions' => array(
                            'edit' => function($row){
                                return Icon::edit(
                                    $this->url('Block:Admin:Block@editAction', $row['id']),
                                    $this->translate('Edit this block')
                                );
                            },

                            'remove' => $extendedMode ? function($row){
                                return Icon::remove(
                                    $this->url('Block:Admin:Block@deleteAction', $row['id']),
                                    $this->translate('Remove this block')
                                );
                            } : null
                        )
                    ))); ?>

                    <?php if (empty($blocks)): ?>
                    <div class="center-block">
                        <h2 class="text-center text-muted"><i class="glyphicon glyphicon-remove"></i> <?php $this->show('No blocks'); ?></h2>
                    </div>
                    <?php endif; ?>
                </div>
            </form>

            <?php $this->loadPartial('paginator'); ?>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card">
            <h2 class="mb-3"><i class="fas fa-tags"></i> <?php $this->show('Categories'); ?> <small>(<?= count($categories); ?>)</small></h2>

            <?= $this->widget(new GridViewWidget($categories, array(
                'pk' => 'id',
                'tableClass' => 'table table-hover table-bordered table-striped',
                'columns' => array(
                    array(
                        'column' => 'id',
                        'label' => '#',
                        'attributes' => array(
                            'class' => 'text-center text-muted'
                        )
                    ),

                    array(
                        'column' => 'name',
                        'attributes' => array(
                            'class' => null
                        )
                    ),

                    array(
                        'column' => 'field_count',
                        'label' => 'Field count'
                    )
                ),

                'actions' => array(
                    'edit' => function($row){
                        return Icon::edit(
                            $this->url('Block:Admin:Category@editAction', $row['id']),
                            $this->translate('Edit this category')
                        );
                    },

                    'remove' => function($row){
                        return Icon::remove(
                            $this->url('Block:Admin:Category@deleteAction', $row['id']),
                            $this->translate('Remove this category')
                        );
                    }
                )
            ))); ?>
        </div>
    </div>
</div>

