<?php

use Block\View\FieldMaker;

?>

<?php if (!empty($fields)): ?>
<div role="tabpanel" class="tab-pane" id="block-fields">
    <ul class="nav nav-tabs" role="tablist">
        <?php if (!empty($fields['data']['regular'])): ?>
        <li role="presentation" class="nav-item">
            <a class="nav-link active" href="#fields-main" role="tab" data-bs-toggle="tab"><?= $this->translate('Shared fields') ?></a>
        </li>
        <?php endif; ?>

        <?php if (!empty($fields['data']['translatable'])): ?>
        <?php foreach ($languages as $index => $language): ?>
        <li role="presentation" class="nav-item">
            <a class="nav-link" href="#field-language-<?= $language->getId() ?>" role="tab" data-bs-toggle="tab"><?= $this->translate('Fields') ?> <small>(<?= $language->getName() ?>)</small></a>
        </li>
        <?php endforeach; ?>
        <?php endif; ?>
    </ul>

    <div class="tab-content">
        <?php if (isset($fields['data']['regular'])): ?>
        <div role="tabpanel" class="tab-pane active show" id="fields-main">
            <?php foreach ($fields['data']['regular'] as $category => $items): ?>
              <fieldset>
                <legend class="container"><?= $category ?></legend>

                <?php foreach ($items as $item): ?>
                <div class="mb-3 row">
                    <label class="col-lg-12 col-form-label"><?= $item['name'] ?> <small class="text-muted">( ID = <?= $item['id'] ?> )</small></label>

                    <div class="col-lg-10">
                        <?php $this->loadPartial('block-file-field', [
                            'value' => $item['value'],
                            'id' => $item['id'],
                            'type' => $item['type']
                        ]); ?>

                        <?= FieldMaker::makeRegularField($item['id'], $item['value'], $item['type']) ?>
                    </div>
                </div>
                <?php endforeach; ?>
              </fieldset>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>

        <?php if (isset($fields['data']['translatable'])): ?>
        <?php foreach ($languages as $index => $language): ?>
        <div role="tabpanel" class="tab-pane" id="field-language-<?= $language->getId() ?>">
            <?php $this->loadPartial('language-name', ['language' => $language]); ?>

            <?php foreach ($fields['data']['translatable'] as $category => $items): ?>
              <fieldset>
                <legend class="container"><?= $category ?></legend>

                <?php foreach ($items as $item): ?>
                <?php $value = $item['translations'][$language->getId()] ?? null ?>
                <div class="mb-3 row">
                    <label class="col-lg-12 col-form-label"><?= $item['name'] ?> <small class="text-muted">( ID = <?= $item['id'] ?> )</small></label>

                    <div class="col-lg-10">
                        <?php $this->loadPartial('block-file-field', [
                            'type' => $item['type'],
                            'id' => $item['id'],
                            'value' => $value
                        ]); ?>

                        <?= FieldMaker::makeTranslatableField($item['id'], $language->getId(), $value, $item['type']) ?>
                    </div>
                </div>
                <?php endforeach; ?>
              </fieldset>
            <?php endforeach; ?>
        </div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>