<?php

use Krystal\Form\Element;

?>

<?php if (isset($blockCategories, $activeBlockCategoryIds) && !empty($blockCategories)): ?>
<div class="mb-3 row">
    <label class="col-lg-12 col-form-label"><?= $this->translate('Attached field categories') ?></label>
    <div class="col-lg-10">
        <?= Element::select('block[]', $blockCategories, $activeBlockCategoryIds, ['multiple' => true, 'class' => 'form-select']) ?>
    </div>
</div>
<?php endif; ?>